version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-50-19-114-27.compute-1.amazonaws.com
            database: d294r54jhqhjlf
            schema: public
            user: hfxpnsrykwfsut
            password: 21dc702c82993b8f64455082156ff5d931644f49b8c992b418a359cc3eec18aa
            ssl: true
            rawAccess: true
            port: '5432'
            migrations: true